### PR TITLE
added '--config' parameter 

### PR DESCRIPTION
**Pull request by punto1**
added '--config' parameter to add an .ini file with any arbitrary name or location; has fallback to the legacy .croncoat.ini file in users' home dir

### CODE REVIEW

**Comment by MatthiasKauer** [comment]
this looks like a meaningful proposition. I'll get to this soon :)

**Comment by punto1** [comment]
Thx for croncoat, just what I needed!

**Comment by MatthiasKauer** [comment]
Thank you for this contribution. It was a great help to get some first test cases running!
May I ask how you found this project?

**Comment by punto1** [comment]
I looked for a dead-man's switch, and via cronwrap I ended up at croncoat :-)

**Pull request merged**
